server:
  port: 8084 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境




#
#jasypt:
#  encryptor:
#    password: ${ENCRYPT_KEY}  # 密钥从环境变量获取
#    algorithm: PBEWithHMACSHA512ANDAES_256  # 推荐使用强加密算法
#    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

